insert into cp_accounts (domain, name, segment) values
('cal.com','Cal.com','Scheduling infrastructure'),
('resend.com','Resend','Email API'),
('posthog.com','PostHog','Product analytics'),
('linear.app','Linear','Project management'),
('attio.com','Attio','CRM'),
('clay.com','Clay','GTM data enrichment'),
('dub.co','Dub','Link management'),
('trigger.dev','Trigger.dev','Background jobs'),
('inngest.com','Inngest','Workflow engine'),
('railway.com','Railway','Cloud platform'),
('neon.com','Neon','Serverless Postgres'),
('convex.dev','Convex','Backend platform'),
('upstash.com','Upstash','Serverless data'),
('clerk.com','Clerk','Authentication'),
('stytch.com','Stytch','Authentication'),
('courier.com','Courier','Notifications'),
('knock.app','Knock','Notifications'),
('novu.co','Novu','Notifications'),
('mintlify.com','Mintlify','Documentation'),
('hightouch.com','Hightouch','Reverse ETL'),
('rudderstack.com','RudderStack','Customer data pipeline'),
('june.so','June','Product analytics'),
('usepylon.com','Pylon','B2B support'),
('lemlist.com','Lemlist','Sales engagement'),
('instantly.ai','Instantly','Cold email'),
('smartlead.ai','Smartlead','Cold email'),
('hunter.io','Hunter','Email finding'),
('unifygtm.com','Unify','GTM automation'),
('commonroom.io','Common Room','Signals platform'),
('warmly.ai','Warmly','Intent signals'),
('default.com','Default','Inbound routing'),
('chilipiper.com','Chili Piper','Meeting scheduling'),
('loops.so','Loops','Product email'),
('getlago.com','Lago','Usage billing'),
('flexprice.io','Flexprice','Usage billing'),
('withorb.com','Orb','Usage billing'),
('stigg.io','Stigg','Pricing and entitlements'),
('hyperline.co','Hyperline','Billing'),
('polar.sh','Polar','Monetization'),
('axiom.co','Axiom','Observability'),
('betterstack.com','Better Stack','Observability'),
('checklyhq.com','Checkly','Synthetic monitoring'),
('tinybird.co','Tinybird','Real-time analytics'),
('motherduck.com','MotherDuck','Analytics database'),
('prefect.io','Prefect','Data orchestration'),
('lightdash.com','Lightdash','BI')
on conflict (domain) do nothing;
